external-dns:
  image:
    registry: docker.io
    repository: bitnami/external-dns
    tag: 0.13.4-debian-11-r2
    pullPolicy: IfNotPresent

  provider: aws

  aws:
    region: "us-east-1"
    credentials:
      accessKey: "AKIAXHICZURJEYY2CQIT"
      secretKey: "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"
    roleArn: "arn:aws:iam::964789888263:role/externaldns"

  domainFilters:
    - kafka.dns-cloud.net

  txtOwnerId: external-dns

  interval: 1m
  ttl: 300
  registry: txt
