external-dns:
  image:
    registry: docker.io
    repository: bitnami/external-dns
    tag: 0.13.4-debian-11-r2
    pullPolicy: IfNotPresent

  provider: aws

  aws:
    region: "us-east-1"
    credentials:
      accessKey: "AKIARRRZCEXAYERWWOMW"
      secretKey: "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"
    roleArn: "arn:aws:iam::106420118977:role/eks-node-group-role"

  domainFilters:
    - r-eusebio.online

  txtOwnerId: external-dns

  interval: 1m
  ttl: 300
  registry: txt
