external-dns:
  image:
    registry: docker.io
    repository: bitnami/external-dns
    tag: 0.13.4-debian-11-r2
    pullPolicy: IfNotPresent

  provider: aws

  aws:
    region: "us-east-1"
    credentials:
      accessKey: "AKIA6GPHQ7SD5HRQEOOU"
      secretKey: "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"
    roleArn: "arn:aws:iam::975980002439:role/eks-master-role"

  domainFilters:
    - r-eusebio.online

  txtOwnerId: external-dns

  interval: 1m
  ttl: 300
  registry: txt
